#!/usr/bin/env python3

import click
import json
import os
import subprocess
import tempfile


DOC_PATH = '/home/bob/repos/devdocs/public/docs/javascript/'


@click.command()
@click.argument('search_term')
def doctor(search_term):
    index_file = os.path.join(DOC_PATH, 'index.json')
    with open(index_file) as f:
        index = json.load(f)

    entries = {entry['name']: entry for entry in index['entries']}
    entry = entries[search_term]

    entry_path = entry['path'].split('#')[0]
    doc_path = os.path.join(DOC_PATH, entry_path) + '.html'
    with open(doc_path) as doc:
        process = subprocess.run(
            ['./to-markdown'],
            stdin=doc,
            stdout=subprocess.PIPE,
            universal_newlines=True,
        )
    markdown_doc = process.stdout

    _, temp = tempfile.mkstemp(prefix=entry['name'] + '.', suffix='.md')
    with open(temp, 'w+') as f:
        f.write(markdown_doc)
    subprocess.run(['vim', temp])
    os.remove(temp)


if __name__ == '__main__':
    doctor()
